# This workflow automatically posts a guidance comment on new issues.
# It asks for the details maintainers need to troubleshoot a problem with
# EngineScript Site Exporter.
# The workflow is triggered whenever a new issue is opened.

name: New Issue Guidance

on:
  issues:
    types: [opened]

permissions: read-all

jobs:
  guide:
    runs-on: ubuntu-latest
    # Explicitly define permissions required by the job
    permissions:
      issues: write
    steps:
      - name: Post guidance comment on new issue
        uses: peter-evans/create-or-update-comment@v5
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Thanks for opening an issue. Please provide a detailed description of the problem you're facing. If you have error messages or logs, please include them as well.

            If your server was configured with the main EngineScript application, you can run a detailed log by running the command `es.debug` in your server console. This will generate a detailed log of the current state of the server, which can help us understand the issue better.
